#!/bin/sh
QOOXDOO=${QOOXDOO:-../qooxdoo}
BUILD_PATH="build"

if [ -z "$1" ]; then
    echo ">>> customize: creating index.html"
    cp template/index.html.in source/index.html
else
    echo ">>> customize: preparing index.html for build-final"
    
    [ ! -d $BUILD_PATH/resource/gosa/js ] && mkdir -p $BUILD_PATH/resource/gosa/js

    sed "/BUILD::REMOVE::START/,/BUILD::REMOVE::END/d" \
        template/index.html.in > $BUILD_PATH/index.html
    
    # Loop thru libs and optimize them
    for lib in source/resource/gosa/js/*js; do
      if [ "x$lib" = "xsource/resource/gosa/js/*js" ]; then
	      break
      fi

      libname=$(basename $lib)
      if [ "$libname" = "qrcode.js" ]; then
        echo "  - Copying $libname"
        cp $lib $BUILD_PATH/resource/gosa/js/$libname
      else
        echo "  - Optimizing $libname"
        python2 $QOOXDOO/tool/bin/compile.py -q $lib > $BUILD_PATH/resource/gosa/js/$libname
      fi
    done
fi
